services:
 postgres:
  image: postgres:15
  environment:
   POSTGRES_USER: sales_user
   POSTGRES_PASSWORD: sales_pass
   POSTGRES_DB: sales_db
  ports:
   - '5432:5432'
  volumes:
   - pgdata:/var/lib/postgresql/data
  healthcheck:
   test: ["CMD-SHELL", "pg_isready -U sales_user"]
   interval: 10s
   timeout: 5s
   retries: 5
volumes:
 pgdata: